services:
  gatus:
    image: gatus-wrapper:latest
    container_name: gatus
    restart: unless-stopped
    environment:
      GATUS_CONFIG_PATH: /tmp/config.yaml
    volumes:
      - ./gatus.yaml:/config/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    networks:
      - gatus-test

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command: serve
    ports:
      - "8090:80"
    networks:
      - gatus-test

  hello:
    image: nginx:alpine
    container_name: hello
    labels:
      gatus.io/enabled: "true"
      gatus.io/url: "http://hello:1234"
    networks:
      - gatus-test

networks:
  gatus-test:
    driver: bridge
